version: '3.9'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
